# Generated by Django 5.2.3 on 2025-08-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
