# Generated by Django 5.2.3 on 2025-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0008_learningplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningPlan',
        ),
    ]
