# Generated by Django 5.2.3 on 2025-08-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0010_learningplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='chapters_per_day',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
