# Generated by Django 5.2.3 on 2025-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0012_quizquestion_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='days',
            field=models.CharField(default='', max_length=100),
        ),
    ]
