# Generated by Django 5.2.3 on 2025-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0014_question_post_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='category_pics/'),
        ),
    ]
