# Generated by Django 5.2.3 on 2025-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0018_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
