# Generated by Django 5.2.3 on 2025-08-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0019_chapter_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='is_completed',
            new_name='user_completed',
        ),
    ]
