# Generated by Django 5.2.3 on 2025-08-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0021_chapter_completed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='completed_user',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='user_completed',
        ),
    ]
