# Generated by Django 5.2.5 on 2025-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0023_userchapterprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='daily_chapters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
