# Generated by Django 5.2.5 on 2025-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0024_learningplan_daily_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='quiz_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
