# Generated by Django 5.2.5 on 2025-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0025_learningplan_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
