# Generated by Django 5.2.5 on 2025-10-12 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelab_app', '0026_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consecutive_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
